import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.control.ComboBox;

/** Created by GuoJunjun <junjunguo.com> on 16.01.15. */

public class Countries {

    public static ComboBox addComboBox() {

        ObservableList<String> countries = FXCollections.observableArrayList(
                "CNY - Yuan Renminbi - China - Beijing" ,
                "USD - US Dollar - United-States - Washington" ,
                "EUR - Euro - European-Union - Brussels" ,
                "GBP - Pound Sterling - United-Kingdom - London" ,
                "NOK - Norwegian Krone - Norway - Oslo" ,
                "SEK - Swedish Krona - Sweden - Stockholm" ,
                "DKK - Danish Krone - Denmark - Copenhagen" ,
                "INR - Indian Rupee - India - New Delhi" ,
                "AUD - Australian Dollar - Australia - Canberra" ,
                "CAD - Canadian Dollar - Canada - Ottawa" ,
                "SGD - Singapore Dollar - Singapore - Singapore" ,
                "CHF - Swiss Franc - Switzerland - Bern" ,
                "MYR - Malaysian Ringgit - Malaysia - Kuala Lumpur" ,
                "JPY - Japanese Yen - Japan - Tokyo" ,
                "NZD - New Zealand Dollar - New-Zealand - Wellington" ,
                "HKD - Hong Kong Dollar - Hong-Kong - Victoria" ,
                "CZK - Czech Koruna - Czech-Republic - Prague" ,
                "SAR - Saudi Riyal - Saudi-Arabia - Riyadh" ,
                "AFN - Afghanistan Afghani - Afghanistan - Kabul" ,
                "ALL - Albanian Lek - Albania - Tirana" ,
                "DZD - Algerian Dinar - Algeria - Algiers" ,
                "USD - US Dollar - American-Samoa - Pago Pago" ,
                "EUR - Euro - Andorra - Andorra" ,
                "AOA - Angolan Kwanza - Angola - Luanda" ,
                "XCD - East Caribbean Dollar - Anguilla - The Valley" ,
                "XCD - East Caribbean Dollar - Antigua-and-Barbuda - St. Johns" ,
                "ARS - Argentine Peso - Argentina - Buenos Aires" ,
                "AMD - Armenian Dram - Armenia - Yerevan" ,
                "AWG - Aruban Guilder - Aruba - Oranjestad" ,
                "EUR - Euro - Austria - Vienna" ,
                "AZN - Azerbaijan New Manat - Azerbaijan - Baku" ,
                "BSD - Bahamian Dollar - Bahamas - Nassau" ,
                "BHD - Bahraini Dinar - Bahrain - Al-Manamah" ,
                "BDT - Bangladeshi Taka - Bangladesh - Dhaka" ,
                "BBD - Barbados Dollar - Barbados - Bridgetown" ,
                "BYR - Belarussian Ruble - Belarus - Minsk" ,
                "EUR - Euro - Belgium - Brussels" ,
                "BZD - Belize Dollar - Belize - Belmopan" ,
                "XOF - CFA Franc BCEAO - Benin - Porto-Novo" ,
                "BMD - Bermudian Dollar - Bermuda - Hamilton" ,
                "BTN - Bhutan Ngultrum - Bhutan - Thimphu" ,
                "BOB - Boliviano - Bolivia - La Paz" ,
                "BAM - Marka - Bosnia-and-Herzegovina - Sarajevo" ,
                "BWP - Botswana Pula - Botswana - Gaborone" ,
                "BRL - Brazilian Real - Brazil - Brasilia" ,
                "BND - Brunei Dollar - Brunei - Bandar Seri Begawan" ,
                "BGN - Bulgarian Lev - Bulgaria - Sofia" ,
                "XOF - CFA Franc BCEAO - Burkina-Faso - Ouagadougou" ,
                "BIF - Burundi Franc - Burundi - Bujumbura" ,
                "KHR - Kampuchean Riel - Cambodia - Phnom Penh" ,
                "XAF - CFA Franc BEAC - Cameroon - Yaounde" ,
                "CVE - Cape Verde Escudo - Cape-Verde - Praia" ,
                "KYD - Cayman Islands Dollar - Cayman-Islands - Georgetown" ,
                "XAF - CFA Franc BEAC - Central-African-Republic - Bangui" ,
                "XAF - CFA Franc BEAC - Chad - N'Djamena" ,
                "CLP - Chilean Peso - Chile - Santiago" ,
                "AUD - Australian Dollar - Christmas-Island - The Settlement" ,
                "COP - Colombian Peso - Colombia - Bogota" ,
                "KMF - Comoros Franc - Comoros - Moroni" ,
                "XAF - CFA Franc BEAC - Republic-of-the-Congo - Brazzaville" ,
                "CDF - Francs - Democratic-Republic-of-the-Congo - Kinshasa" ,
                "NZD - New Zealand Dollar - Cook-Islands - Avarua" ,
                "CRC - Costa Rican Colon - Costa-Rica - San Jose" ,
                "HRK - Croatian Kuna - Croatia - Zagreb" ,
                "CUP - Cuban Peso - Cuba - Havana" ,
                "EUR - Euro - Cyprus - Nicosia" ,
                "DJF - Djibouti Franc - Djibouti - Djibouti" ,
                "XCD - East Caribbean Dollar - Dominica - Roseau" ,
                "DOP - Dominican Peso - Dominican-Republic - Santo Domingo" ,
                "ECS - Ecuador Sucre - Ecuador - Quito" ,
                "EGP - Egyptian Pound - Egypt - Cairo" ,
                "SVC - El Salvador Colon - El-Salvador - San Salvador" ,
                "XAF - CFA Franc BEAC - Equatorial-Guinea - Malabo" ,
                "ERN - Eritrean Nakfa - Eritrea - Asmara" ,
                "EUR - Euro - Estonia - Tallinn" ,
                "ETB - Ethiopian Birr - Ethiopia - Addis Ababa" ,
                "DKK - Danish Krone - Faroe-Islands - Torshavn" ,
                "FJD - Fiji Dollar - Fiji - Suva" ,
                "EUR - Euro - Finland - Helsinki" ,
                "EUR - Euro - France - Paris" ,
                "XAF - CFA Franc BEAC - Gabon - Libreville" ,
                "GMD - Gambian Dalasi - Gambia - Banjul" ,
                "GEL - Georgian Lari - Georgia - Tbilisi" ,
                "EUR - Euro - Germany - Berlin" ,
                "GHS - Ghanaian Cedi - Ghana - Accra" ,
                "GIP - Gibraltar Pound - Gibraltar - Gibraltar" ,
                "EUR - Euro - Greece - Athens" ,
                "DKK - Danish Krone - Greenland - Godthab" ,
                "XCD - East Carribean Dollar - Grenada - St. George's" ,
                "QTQ - Guatemalan Quetzal - Guatemala - Guatemala City" ,
                "GGP - Pound Sterling - Guernsey - St. Peter Port" ,
                "GNF - Guinea Franc - Guinea - Conakry" ,
                "GWP - Guinea-Bissau Peso - Guinea-Bissau - Bissau" ,
                "GYD - Guyana Dollar - Guyana - Georgetown" ,
                "HTG - Haitian Gourde - Haiti - Port-au-Prince" ,
                "HNL - Honduran Lempira - Honduras - Tegucigalpa" ,
                "HUF - Hungarian Forint - Hungary - Budapest" ,
                "ISK - Iceland Krona - Iceland - Reykjavik" ,
                "IDR - Indonesian Rupiah - Indonesia - Jakarta" ,
                "IRR - Iranian Rial - Iran - Tehran" ,
                "IQD - Iraqi Dinar - Iraq - Baghdad" ,
                "EUR - Euro - Ireland - Dublin" ,
                "GBP - Pound Sterling - Isle-of-Man - Douglas" ,
                "ILS - Israeli New Shekel - Israel - Jerusalem" ,
                "EUR - Euro - Italy - Rome" ,
                "XOF - CFA Franc BCEAO - Cote-dIvoire - Abidjan" ,
                "JMD - Jamaican Dollar - Jamaica - Kingston" ,
                "GBP - Pound Sterling - Jersey - Saint Helier" ,
                "JOD - Jordanian Dinar - Jordan - Amman" ,
                "KZT - Kazakhstan Tenge - Kazakhstan - Astana" ,
                "KES - Kenyan Shilling - Kenya - Nairobi" ,
                "AUD - Australian Dollar - Kiribati - Tarawa" ,
                "KPW - North Korean Won - North-Korea - Pyongyang" ,
                "KRW - Korean Won - South-Korea - Seoul" ,
                "KWD - Kuwaiti Dinar - Kuwait - Kuwait City" ,
                "KGS - Som - Kyrgyzstan - Bishkek" ,
                "LAK - Lao Kip - Laos - Vientiane" ,
                "LVL - Latvian Lats - Latvia - Riga" ,
                "LBP - Lebanese Pound - Lebanon - Beirut" ,
                "LSL - Lesotho Loti - Lesotho - Maseru" ,
                "LRD - Liberian Dollar - Liberia - Monrovia" ,
                "LYD - Libyan Dinar - Libya - Tripoli" ,
                "CHF - Swiss Franc - Liechtenstein - Vaduz" ,
                "LTL - Lithuanian Litas - Lithuania - Vilnius" ,
                "EUR - Euro - Luxembourg - Luxembourg" ,
                "MOP - Macau Pataca - Macau - Macau" ,
                "MKD - Denar - Macedonia - Skopje" ,
                "MGF - Malagasy Franc - Madagascar - Antananarivo" ,
                "MWK - Malawi Kwacha - Malawi - Lilongwe" ,
                "MVR - Maldive Rufiyaa - Maldives - Male" ,
                "XOF - CFA Franc BCEAO - Mali - Bamako" ,
                "EUR - Euro - Malta - Valletta" ,
                "USD - US Dollar - Marshall-Islands - Majuro" ,
                "MRO - Mauritanian Ouguiya - Mauritania - Nouakchott" ,
                "MUR - Mauritius Rupee - Mauritius - Port Louis" ,
                "EUR - Euro - Mayotte - Dzaoudzi" ,
                "MXN - Mexican Nuevo Peso - Mexico - Mexico City" ,
                "USD - US Dollar - Micronesia - Palikir" ,
                "MDL - Moldovan Leu - Moldova - Kishinev" ,
                "EUR - Euro - Monaco - Monaco" ,
                "MNT - Mongolian Tugrik - Mongolia - Ulan Bator" ,
                "EUR - Euro - Montenegro - Podgorica" ,
                "XCD - East Caribbean Dollar - Montserrat - Plymouth" ,
                "MAD - Moroccan Dirham - Morocco - Rabat" ,
                "MZN - Mozambique Metical - Mozambique - Maputo" ,
                "MMK - Myanmar Kyat - Myanmar - Naypyidaw" ,
                "NAD - Namibian Dollar - Namibia - Windhoek" ,
                "AUD - Australian Dollar - Nauru - Yaren" ,
                "NPR - Nepalese Rupee - Nepal - Kathmandu" ,
                "EUR - Euro - Netherlands - Amsterdam" ,
                "ANG - Netherlands Antillean Guilder - Netherlands-Antilles - Willemstad" ,
                "NIO - Nicaraguan Cordoba Oro - Nicaragua - Managua" ,
                "XOF - CFA Franc BCEAO - Niger - Niamey" ,
                "NGN - Nigerian Naira - Nigeria - Lagos" ,
                "NZD - New Zealand Dollar - Niue - Alofi" ,
                "AUD - Australian Dollar - Norfolk-Island - Kingston" ,
                "USD - US Dollar - Northern-Mariana-Islands - Saipan" ,
                "OMR - Omani Rial - Oman - Muscat" ,
                "PKR - Pakistan Rupee - Pakistan - Islamabad" ,
                "USD - US Dollar - Palau - Koror" ,
                "PAB - Panamanian Balboa - Panama - Panama City" ,
                "PGK - Papua New Guinea Kina - Papua-New-Guinea - Port Moresby" ,
                "PYG - Paraguay Guarani - Paraguay - Asuncion" ,
                "PEN - Peruvian Nuevo Sol - Peru - Lima" ,
                "PHP - Philippine Peso - Philippines - Manila" ,
                "NZD - New Zealand Dollar - Pitcairn-Islands - Adamstown" ,
                "PLN - Polish Zloty - Poland - Warsaw" ,
                "EUR - Euro - Portugal - Lisbon" ,
                "USD - US Dollar - Puerto-Rico - San Juan" ,
                "QAR - Qatari Rial - Qatar - Doha" ,
                "RON - Romanian New Leu - Romania - Bucharest" ,
                "RUB - Russian Ruble - Russia - Moscow" ,
                "RWF - Rwanda Franc - Rwanda - Kigali" ,
                "SHP - St. Helena Pound - Saint-Helena - Jamestown" ,
                "XCD - East Caribbean Dollar - Saint-Lucia - Castries" ,
                "WST - Samoan Tala - Samoa - Apia" ,
                "EUR - Euro - San-Marino - San Marino" ,
                "STD - Dobra - Sao-Tome-and-Principe - Sao Tome" ,
                "XOF - CFA Franc BCEAO - Senegal - Dakar" ,
                "RSD - Dinar - Serbia - Belgrade" ,
                "SCR - Seychelles Rupee - Seychelles - Victoria" ,
                "SLL - Sierra Leone Leone - Sierra-Leone - Freetown" ,
                "EUR - Euro - Slovakia - Bratislava" ,
                "EUR - Euro - Slovenia - Ljubljana" ,
                "SBD - Solomon Islands Dollar - Solomon-Islands - Honiara" ,
                "SOS - Somali Shilling - Somalia - Mogadishu" ,
                "ZAR - South African Rand - South-Africa - Pretoria" ,
                "SSP - South Sudan Pound - South-Sudan - Ramciel" ,
                "EUR - Euro - Spain - Madrid" ,
                "LKR - Sri Lanka Rupee - Sri-Lanka - Colombo" ,
                "SDG - Sudanese Pound - Sudan - Khartoum" ,
                "SRD - Surinam Dollar - Suriname - Paramaribo" ,
                "SZL - Swaziland Lilangeni - Swaziland - Mbabane" ,
                "SYP - Syrian Pound - Syria - Damascus" ,
                "TWD - Taiwan Dollar - Taiwan - Taipei" ,
                "TJS - Tajik Somoni - Tajikistan - Dushanbe" ,
                "TZS - Tanzanian Shilling - Tanzania - Dodoma" ,
                "THB - Thai Baht - Thailand - Bangkok" ,
                "XOF - CFA Franc BCEAO - Togo - Lome" ,
                "TOP - Tongan Pa'anga - Tonga - Nuku'alofa" ,
                "TTD - Trinidad and Tobago Dollar - Trinidad-and-Tobago - Port of Spain" ,
                "TND - Tunisian Dollar - Tunisia - Tunis" ,
                "TRY - Turkish Lira - Turkey - Ankara" ,
                "TMT - Manat - Turkmenistan - Ashgabat" ,
                "USD - US Dollar - Turks-and-Caicos-Islands - Grand Turk" ,
                "AUD - Australian Dollar - Tuvalu - Funafuti" ,
                "UGX - Uganda Shilling - Uganda - Kampala" ,
                "UAH - Ukraine Hryvnia - Ukraine - Kiev" ,
                "AED - Arab Emirates Dirham - United-Arab-Emirates - Abu Dhabi" ,
                "UYU - Uruguayan Peso - Uruguay - Montevideo" ,
                "UZS - Uzbekistan Sum - Uzbekistan - Tashkent" ,
                "VUV - Vanuatu Vatu - Vanuatu - Port Vila" ,
                "EUR - Euro - Vatican-City - Vatican City" ,
                "VEF - Venezuelan Bolivar - Venezuela - Caracas" ,
                "VND - Vietnamese Dong - Vietnam - Hanoi" ,
                "MAD - Moroccan Dirham - Western-Sahara - El Aaiun" ,
                "YER - Yemeni Rial - Yemen - San'a" ,
                "ZMW - Zambian Kwacha - Zambia - Lusaka" ,
                "ZWD - Zimbabwe Dollar - Zimbabwe - Harare"
        );
        return new ComboBox(countries);
    }
}
